#!/usr/bin/env bash
# Collect a privacy-conscious, read-only hardware baseline for RP Mini V2.

set -u
set -o pipefail

SCRIPT_VERSION="1"
OUTPUT=""
SELF_TEST=0
SYS_ROOT="${SYS_ROOT:-/sys}"
PROC_ROOT="${PROC_ROOT:-/proc}"

usage() {
    cat <<'EOF'
Usage: rpmini-v2-support-bundle.sh [--output DIRECTORY]
       rpmini-v2-support-bundle.sh --self-test

Collects read-only hardware and limited system diagnostics. It never reads
network connection profiles, IP/MAC address files, user journals, environment
variables, device serial files, or disk UUIDs. Review the output before sharing.
EOF
}

redact() {
    LC_ALL=C sed -E \
        -e 's/([[:xdigit:]]{2}:){5}[[:xdigit:]]{2}/<MAC>/g' \
        -e 's/([[:xdigit:]]{2}[_-]){5}[[:xdigit:]]{2}/<MAC>/g' \
        -e 's/wlx[[:xdigit:]]{12}/wlx<MAC>/g' \
        -e 's/([0-9]{1,3}\.){3}[0-9]{1,3}/<IPv4>/g' \
        -e 's/([[:xdigit:]]{1,4}:){1,7}:([[:xdigit:]]{1,4}(:[[:xdigit:]]{1,4}){0,6})?/<IPv6>/g' \
        -e 's/::([[:xdigit:]]{1,4}:){0,6}[[:xdigit:]]{1,4}/<IPv6>/g' \
        -e 's/([[:xdigit:]]{1,4}:){7}[[:xdigit:]]{1,4}/<IPv6>/g' \
        -e 's/[[:xdigit:]]{8}-[[:xdigit:]]{4}-[[:xdigit:]]{4}-[[:xdigit:]]{4}-[[:xdigit:]]{12}/<UUID>/g' \
        -e 's#(/var)?/home/[^/[:space:]]+#\1/home/<USER>#g' \
        -e 's/((SSID|ssid|BSSID|bssid)[^:=]*[:=])[[:space:]]*.*/\1 <REDACTED>/' \
        -e "s/((SSID|ssid)[[:space:]]+)'[^']*'/\1'<REDACTED>'/g" \
        -e 's/((PSK|psk|password|Password|passphrase|Passphrase|token|Token|secret|Secret|credential|Credential)[^:=]*[:=])[[:space:]]*.*/\1 <REDACTED>/' \
        -e 's/((serial|Serial|SERIAL|uniq|Uniq|UNIQ)[^:=]*[:=])[[:space:]]*[^[:space:]]+/\1 <REDACTED>/g' \
        -e 's/(LABEL|label)=[^[:space:]]+/\1=<REDACTED>/g' \
        -e "s/((LABEL|label)[[:space:]]+)'[^']*'/\1'<REDACTED>'/g"
}

run_self_test() {
    local sample output secret
    sample='address=aa:bb:cc:dd:ee:ff alt=aa_bb_cc_dd_ee_ff ip=192.168.5.20 ipv6=fe80::1234 UUID=12345678-1234-4abc-8def-1234567890ab
collected_at_utc: 2026-07-11T07:24:35Z
SSID: private-network
password=correct-horse
Serial Number: ABCD1234
/home/alice/save.dat'
    output="$(printf '%s\n' "$sample" | redact)"

    for secret in \
        'aa:bb:cc:dd:ee:ff' \
        'aa_bb_cc_dd_ee_ff' \
        '192.168.5.20' \
        'fe80::1234' \
        '12345678-1234-4abc-8def-1234567890ab' \
        'private-network' \
        'correct-horse' \
        'ABCD1234' \
        '/home/alice'; do
        if printf '%s\n' "$output" | grep -F -- "$secret" >/dev/null; then
            printf 'redaction self-test failed: leaked synthetic value\n' >&2
            return 1
        fi
    done

    for marker in '<MAC>' '<IPv4>' '<IPv6>' '<UUID>' '<REDACTED>' '/home/<USER>'; do
        if ! printf '%s\n' "$output" | grep -F -- "$marker" >/dev/null; then
            printf 'redaction self-test failed: missing %s\n' "$marker" >&2
            return 1
        fi
    done

    if ! printf '%s\n' "$output" | grep -F -- '2026-07-11T07:24:35Z' >/dev/null; then
        printf 'redaction self-test failed: ISO timestamp was corrupted\n' >&2
        return 1
    fi

    printf 'redaction self-test: PASS\n'
}

while [ "$#" -gt 0 ]; do
    case "$1" in
        --output)
            if [ "$#" -lt 2 ] || [ -z "$2" ]; then
                printf '%s\n' '--output requires a directory' >&2
                exit 2
            fi
            OUTPUT="$2"
            shift 2
            ;;
        --self-test)
            SELF_TEST=1
            shift
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        *)
            printf 'unknown argument: %s\n' "$1" >&2
            usage >&2
            exit 2
            ;;
    esac
done

if [ "$SELF_TEST" -eq 1 ]; then
    run_self_test
    exit $?
fi

if [ -z "$OUTPUT" ]; then
    OUTPUT="./rpmini-v2-support-$(date -u +%Y%m%dT%H%M%SZ)"
fi

if [ -e "$OUTPUT" ]; then
    printf 'refusing to overwrite existing path: %s\n' "$OUTPUT" >&2
    exit 1
fi

umask 077
mkdir -p -- "$(dirname -- "$OUTPUT")" || exit 1
mkdir -- "$OUTPUT" || exit 1

cleanup() {
    find "$OUTPUT" -maxdepth 1 -type f -name '.*.raw' -delete 2>/dev/null || true
}
trap cleanup EXIT HUP INT TERM

capture() {
    local filename title raw status
    filename="$1"
    title="$2"
    shift 2
    raw="$OUTPUT/.${filename}.raw"

    {
        printf '# %s\n' "$title"
        printf '# generated by rpmini-v2-support-bundle.sh v%s\n\n' "$SCRIPT_VERSION"
        "$@"
        status=$?
        printf '\n# collector-exit-status: %s\n' "$status"
    } >"$raw" 2>&1

    if ! redact <"$raw" >"$OUTPUT/$filename"; then
        rm -f -- "$raw" "$OUTPUT/$filename"
        printf 'redaction failed while collecting %s\n' "$filename" >&2
        exit 1
    fi
    rm -f -- "$raw"
}

read_value() {
    local path
    path="$1"
    if [ -r "$path" ]; then
        tr '\000' '\n' <"$path"
    else
        printf '<unavailable: %s>\n' "$path"
    fi
}

show_field() {
    local root field
    root="$1"
    field="$2"
    if [ -r "$root/$field" ]; then
        printf '%s: ' "$field"
        tr '\000' '\n' <"$root/$field"
    fi
}

collect_system() {
    printf 'collected_at_utc: %s\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
    printf 'collector_euid: %s\n' "${EUID:-unknown}"
    printf 'kernel_system: %s\n' "$(uname -s 2>/dev/null || printf unavailable)"
    printf 'kernel_release: %s\n' "$(uname -r 2>/dev/null || printf unavailable)"
    printf 'machine: %s\n' "$(uname -m 2>/dev/null || printf unavailable)"
    if [ -r /etc/os-release ]; then
        printf '\n[os-release]\n'
        sed -n -E '/^(NAME|ID|ID_LIKE|VERSION|VERSION_ID|VARIANT|VARIANT_ID)=/p' /etc/os-release
    fi
    if command -v systemd-detect-virt >/dev/null 2>&1; then
        printf '\nvirtualization: '
        systemd-detect-virt 2>/dev/null || printf 'none\n'
    fi
}

collect_dt() {
    printf '[model]\n'
    read_value "$PROC_ROOT/device-tree/model"
    printf '\n[compatible]\n'
    read_value "$PROC_ROOT/device-tree/compatible"

    if [ -r "$SYS_ROOT/firmware/fdt" ]; then
        printf '\n[fdt-sha256]\n'
        if command -v sha256sum >/dev/null 2>&1; then
            sha256sum "$SYS_ROOT/firmware/fdt"
        elif command -v shasum >/dev/null 2>&1; then
            shasum -a 256 "$SYS_ROOT/firmware/fdt"
        else
            printf '<sha256 tool unavailable>\n'
        fi
    fi

    printf '\n[top-level-nodes]\n'
    if [ -d "$PROC_ROOT/device-tree" ]; then
        find "$PROC_ROOT/device-tree" -mindepth 1 -maxdepth 1 -type d -print 2>/dev/null |
            while IFS= read -r node; do
                printf '%s\n' "${node#"$PROC_ROOT/device-tree/"}"
            done | LC_ALL=C sort
    else
        printf '<device tree unavailable>\n'
    fi
}

collect_drm() {
    local node connector name field driver
    for node in "$SYS_ROOT"/class/drm/card[0-9]*; do
        [ -e "$node" ] || continue
        name="$(basename -- "$node")"
        case "$name" in
            *-*) continue ;;
        esac
        printf '[%s]\n' "$name"
        driver="$(readlink "$node/device/driver" 2>/dev/null || true)"
        [ -n "$driver" ] && printf 'driver: %s\n' "${driver##*/}"
        show_field "$node/device" modalias
        printf '\n'
    done

    for connector in "$SYS_ROOT"/class/drm/card*-*; do
        [ -e "$connector" ] || continue
        name="$(basename -- "$connector")"
        printf '[%s]\n' "$name"
        for field in status enabled dpms modes; do
            show_field "$connector" "$field"
        done
        printf '\n'
    done
}

collect_input() {
    local event root name field
    if [ -r "$PROC_ROOT/bus/input/devices" ]; then
        printf '[proc-bus-input-devices]\n'
        cat "$PROC_ROOT/bus/input/devices"
    else
        printf '<%s/bus/input/devices unavailable>\n' "$PROC_ROOT"
    fi

    printf '\n[sysfs-event-devices]\n'
    for event in "$SYS_ROOT"/class/input/event*; do
        [ -e "$event" ] || continue
        name="$(basename -- "$event")"
        root="$event/device"
        printf '\n[%s]\n' "$name"
        for field in name phys modalias; do
            show_field "$root" "$field"
        done
        for field in bustype vendor product version; do
            show_field "$root/id" "$field"
        done
        for field in ev key rel abs ff sw; do
            show_field "$root/capabilities" "$field"
        done
    done
}

collect_network() {
    local iface root name driver field
    if command -v rfkill >/dev/null 2>&1; then
        printf '[rfkill]\n'
        rfkill list 2>&1
    else
        printf '[rfkill]\n<command unavailable>\n'
    fi

    printf '\n[interfaces-without-addresses]\n'
    for iface in "$SYS_ROOT"/class/net/*; do
        [ -e "$iface" ] || continue
        name="$(basename -- "$iface")"
        root="$iface"
        printf '\n[%s]\n' "$name"
        for field in type operstate carrier mtu; do
            show_field "$root" "$field"
        done
        driver="$(readlink "$root/device/driver" 2>/dev/null || true)"
        [ -n "$driver" ] && printf 'driver: %s\n' "${driver##*/}"
        show_field "$root/device" modalias
        if command -v ethtool >/dev/null 2>&1; then
            ethtool -i "$name" 2>&1 || true
        fi
    done

    if command -v iw >/dev/null 2>&1; then
        printf '\n[wireless-phy-capabilities]\n'
        iw phy 2>&1 || true
        printf '\n[wireless-regulatory-domain]\n'
        iw reg get 2>&1 || true
    fi
}

collect_audio() {
    local file card
    for file in cards devices pcm modules; do
        if [ -r "$PROC_ROOT/asound/$file" ]; then
            printf '[proc-asound-%s]\n' "$file"
            cat "$PROC_ROOT/asound/$file"
            printf '\n'
        fi
    done

    if command -v aplay >/dev/null 2>&1; then
        printf '[aplay-hardware]\n'
        aplay -l 2>&1 || true
        printf '\n'
    fi
    if command -v arecord >/dev/null 2>&1; then
        printf '[arecord-hardware]\n'
        arecord -l 2>&1 || true
        printf '\n'
    fi

    printf '[sound-card-components]\n'
    for card in "$SYS_ROOT"/class/sound/card[0-9]*; do
        [ -e "$card" ] || continue
        printf '\n[%s]\n' "$(basename -- "$card")"
        show_field "$card" id
        show_field "$card/device" components
        show_field "$card/device" modalias
    done
}

collect_power() {
    local supply field
    for supply in "$SYS_ROOT"/class/power_supply/*; do
        [ -e "$supply" ] || continue
        printf '[%s]\n' "$(basename -- "$supply")"
        for field in \
            type status health present online capacity capacity_level \
            technology manufacturer model_name cycle_count \
            voltage_now voltage_min_design voltage_max_design \
            current_now current_max power_now charge_now charge_full \
            charge_full_design energy_now energy_full energy_full_design \
            temp time_to_empty_now time_to_full_now; do
            show_field "$supply" "$field"
        done
        printf '\n'
    done
}

collect_thermal() {
    local zone hwmon field input label
    printf '[thermal-zones]\n'
    for zone in "$SYS_ROOT"/class/thermal/thermal_zone*; do
        [ -e "$zone" ] || continue
        printf '\n[%s]\n' "$(basename -- "$zone")"
        show_field "$zone" type
        show_field "$zone" temp
        for input in "$zone"/trip_point_*_temp "$zone"/trip_point_*_type; do
            [ -r "$input" ] || continue
            printf '%s: ' "$(basename -- "$input")"
            cat "$input"
        done
    done

    printf '\n[hwmon]\n'
    for hwmon in "$SYS_ROOT"/class/hwmon/hwmon*; do
        [ -e "$hwmon" ] || continue
        printf '\n[%s]\n' "$(basename -- "$hwmon")"
        show_field "$hwmon" name
        for input in \
            "$hwmon"/temp*_input "$hwmon"/temp*_max "$hwmon"/temp*_crit \
            "$hwmon"/fan*_input "$hwmon"/fan*_target "$hwmon"/pwm*; do
            [ -r "$input" ] || continue
            label="$(basename -- "$input")"
            case "$label" in
                *_enable|pwm*_mode) ;;
            esac
            printf '%s: ' "$label"
            cat "$input"
        done
    done
}

collect_frequency() {
    local policy dev field table
    printf '[cpu-cpufreq]\n'
    for policy in "$SYS_ROOT"/devices/system/cpu/cpufreq/policy*; do
        [ -e "$policy" ] || continue
        printf '\n[%s]\n' "$(basename -- "$policy")"
        for field in \
            affected_cpus related_cpus scaling_driver scaling_governor \
            scaling_available_governors scaling_available_frequencies \
            cpuinfo_min_freq cpuinfo_max_freq cpuinfo_cur_freq \
            scaling_min_freq scaling_max_freq scaling_cur_freq; do
            show_field "$policy" "$field"
        done
        table="$policy/stats/time_in_state"
        if [ -r "$table" ]; then
            printf 'time_in_state:\n'
            cat "$table"
        fi
    done

    printf '\n[devfreq]\n'
    for dev in "$SYS_ROOT"/class/devfreq/*; do
        [ -e "$dev" ] || continue
        printf '\n[%s]\n' "$(basename -- "$dev")"
        for field in \
            name governor available_governors available_frequencies \
            min_freq max_freq cur_freq target_freq load polling_interval; do
            show_field "$dev" "$field"
        done
        table="$dev/trans_stat"
        if [ -r "$table" ]; then
            printf 'trans_stat:\n'
            cat "$table"
        fi
    done
}

collect_storage() {
    local node name sectors bytes parent removable ro rotational model
    local source target fstype options access resolved

    if command -v lsblk >/dev/null 2>&1; then
        printf '[lsblk-no-identifiers]\n'
        lsblk -e 7 -o NAME,KNAME,MAJ:MIN,SIZE,TYPE,FSTYPE,FSVER,RO,RM,ROTA,TRAN,MODEL,PARTTYPE 2>&1 ||
            lsblk -e 7 -o NAME,MAJ:MIN,SIZE,TYPE,FSTYPE,RO,RM,ROTA,MODEL 2>&1
    else
        printf '[lsblk-no-identifiers]\n<command unavailable>\n'

        printf '\n[sysfs-block-fallback]\n'
        for node in "$SYS_ROOT"/class/block/*; do
            [ -e "$node" ] || continue
            name="$(basename -- "$node")"
            case "$name" in
                loop*|ram*|zram*) continue ;;
            esac

            sectors="$(cat "$node/size" 2>/dev/null || printf 0)"
            case "$sectors" in
                ''|*[!0-9]*) bytes='<unavailable>' ;;
                *) bytes=$((sectors * 512)) ;;
            esac
            removable="$(cat "$node/removable" 2>/dev/null || printf unavailable)"
            ro="$(cat "$node/ro" 2>/dev/null || printf unavailable)"
            rotational="$(cat "$node/queue/rotational" 2>/dev/null || printf unavailable)"
            model="$(cat "$node/device/model" 2>/dev/null || true)"

            parent='-'
            if [ -r "$node/partition" ]; then
                parent="$(basename -- "$(dirname -- "$(readlink -f "$node")")")"
            fi

            printf '%s bytes=%s parent=%s ro=%s rm=%s rota=%s' \
                "$name" "$bytes" "$parent" "$ro" "$removable" "$rotational"
            [ -n "$model" ] && printf ' model=%s' "$model"
            printf '\n'
        done
    fi

    if [ -r "$PROC_ROOT/partitions" ]; then
        printf '\n[proc-partitions]\n'
        cat "$PROC_ROOT/partitions"
    fi

    if command -v findmnt >/dev/null 2>&1; then
        printf '\n[known-filesystems-findmnt]\n'
        for target in / /flash /storage /boot /boot/efi; do
            findmnt -n -o MAJ:MIN,FSTYPE,TARGET,VFS-OPTIONS "$target" 2>/dev/null || true
        done
    elif [ -r "$PROC_ROOT/mounts" ]; then
        printf '\n[known-filesystems-proc-fallback]\n'
        while read -r source target fstype options _; do
            case "$target" in
                /|/flash|/storage|/boot|/boot/efi) ;;
                *) continue ;;
            esac

            resolved="$source"
            case "$source" in
                /dev/*)
                    resolved="$(readlink -f "$source" 2>/dev/null || printf '%s' "$source")"
                    ;;
            esac
            case ",$options," in
                *,rw,*) access=rw ;;
                *,ro,*) access=ro ;;
                *) access=unknown ;;
            esac
            printf 'source=%s target=%s fstype=%s access=%s\n' \
                "$resolved" "$target" "$fstype" "$access"
        done <"$PROC_ROOT/mounts"
    fi
}

collect_kernel_journal() {
    if command -v journalctl >/dev/null 2>&1; then
        if journalctl --help 2>&1 | grep -F -- '--no-hostname' >/dev/null; then
            journalctl --no-pager --no-hostname -b -k -n 5000 -o short-monotonic 2>&1
        elif command -v dmesg >/dev/null 2>&1; then
            printf '<journalctl lacks --no-hostname; using kernel ring buffer>\n'
            dmesg 2>&1
        else
            printf '<journal skipped: hostname-free output is unavailable>\n'
        fi
    elif command -v dmesg >/dev/null 2>&1; then
        dmesg 2>&1
    else
        printf '<journalctl and dmesg unavailable>\n'
    fi
}

collect_service_journal() {
    if command -v journalctl >/dev/null 2>&1; then
        if journalctl --help 2>&1 | grep -F -- '--no-hostname' >/dev/null; then
            journalctl --no-pager --no-hostname -b -n 2000 -o short-monotonic \
                -u inputplumber.service \
                -u armada-powerd.service \
                -u power-profiles-daemon.service 2>&1
        else
            printf '<service journal skipped: journalctl lacks --no-hostname>\n'
        fi
    else
        printf '<journalctl unavailable>\n'
    fi
}

capture system.txt 'Kernel and operating-system versions (hostname omitted)' collect_system
capture device-tree.txt 'Device-tree identity' collect_dt
capture drm.txt 'DRM connectors and modes (EDID omitted)' collect_drm
capture input.txt 'Kernel input inventory (unique identifiers redacted)' collect_input
capture network.txt 'Network drivers/radios without addresses, SSIDs or profiles' collect_network
capture audio.txt 'ALSA hardware inventory' collect_audio
capture power.txt 'Power-supply telemetry (serial fields omitted)' collect_power
capture thermal.txt 'Thermal, fan and hwmon telemetry' collect_thermal
capture frequency.txt 'CPU and devfreq limits/current values' collect_frequency
capture storage.txt 'Block topology without UUIDs, labels, serials or user mounts' collect_storage
capture journal-kernel.txt 'Current-boot kernel journal, limited and redacted' collect_kernel_journal
capture journal-hardware-services.txt 'Current-boot hardware-service journal, limited and redacted' collect_service_journal

cat >"$OUTPUT/REVIEW-BEFORE-SHARING.txt" <<'EOF'
This bundle intentionally omits common credentials and personal identifiers and
applies best-effort redaction to collected logs. Automated redaction cannot
guarantee anonymity. Review every file before sharing it.

Not collected: connection profiles, IP/MAC address files, SSIDs, disk UUIDs,
serial-number sysfs files, machine ID, hostname, environment variables, user
journals, application lists, home-directory contents, Android data or keys.
EOF

if command -v sha256sum >/dev/null 2>&1; then
    (
        cd "$OUTPUT" || exit 1
        find . -maxdepth 1 -type f ! -name MANIFEST.sha256 -print0 |
            LC_ALL=C sort -z |
            xargs -0 sha256sum
    ) >"$OUTPUT/MANIFEST.sha256" 2>/dev/null || true
elif command -v shasum >/dev/null 2>&1; then
    (
        cd "$OUTPUT" || exit 1
        find . -maxdepth 1 -type f ! -name MANIFEST.sha256 -print |
            LC_ALL=C sort |
            while IFS= read -r file; do shasum -a 256 "$file"; done
    ) >"$OUTPUT/MANIFEST.sha256" 2>/dev/null || true
fi

printf 'support bundle created: %s\n' "$OUTPUT"
printf 'review every file before sharing it\n'
